// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/african-x1-home/Current.tsx": () => import("../components/mockups/african-x1-home/Current.tsx"),
  "./components/mockups/african-x1-home/EditorialSplit.tsx": () => import("../components/mockups/african-x1-home/EditorialSplit.tsx")
};
